INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Motorola XOOM™ with Wi-Fi','The Next, Next GenerationExperience the future with Motorola XOOM with Wi-Fi, the world''s first tablet powered by Android 3.0 (Honeycomb).','img/phones/motorola-xoom-with-wi-fi.0.jpg', 717);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('MOTOROLA XOOM™','The Next, Next GenerationExperience the future with MOTOROLA XOOM, the world''s first tablet powered by Android 3.0 (Honeycomb).','img/phones/motorola-xoom.0.jpg', 623);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('MOTOROLA ATRIX™ 4G','MOTOROLA ATRIX 4G the world''s most powerful smartphone.','img/phones/motorola-atrix-4g.0.jpg', 418);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Dell Streak 7','Introducing Dell™ Streak 7. Share photos, videos and movies together. It’s small enough to carry around, big enough to gather around.','img/phones/dell-streak-7.0.jpg', 476);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Samsung Gem™','The Samsung Gem™ brings you everything that you would expect and more from a touch display smart phone – more apps, more features and a more affordable price.','img/phones/samsung-gem.0.jpg', 395);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Dell Venue','The Dell Venue; Your Personal Express Lane to Everything','img/phones/dell-venue.0.jpg', 658);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Nexus S','Fast just got faster with Nexus S. A pure Google experience, Nexus S is the first phone to run Gingerbread (Android 2.3), the fastest version of Android yet.','img/phones/nexus-s.0.jpg', 609);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('LG Axis','Android Powered, Google Maps Navigation, 5 Customizable Home Screens','img/phones/lg-axis.0.jpg', 536);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Samsung Galaxy Tab™','Feel Free to Tab™. The Samsung Galaxy Tab™ brings you an ultra-mobile entertainment experience through its 7” display, high-power processor and Adobe® Flash® Player compatibility.','img/phones/samsung-galaxy-tab.0.jpg', 456);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Samsung Showcase™ a Galaxy S™ phone','The Samsung Showcase™ delivers a cinema quality experience like you’ve never seen before. Its innovative 4” touch display technology provides rich picture brilliance, even outdoors','img/phones/samsung-showcase-a-galaxy-s-phone.0.jpg', 325);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('DROID™ 2 Global by Motorola','The first smartphone with a 1.2 GHz processor and global capabilities.','img/phones/droid-2-global-by-motorola.0.jpg', 440);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('DROID™ Pro by Motorola','The next generation of DOES.','img/phones/droid-pro-by-motorola.0.jpg', 466);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('MOTOROLA BRAVO™ with MOTOBLUR™','An experience to cheer about.','img/phones/motorola-bravo-with-motoblur.0.jpg', 739);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Motorola DEFY™ with MOTOBLUR™','Are you ready for everything life throws your way?','img/phones/motorola-defy-with-motoblur.0.jpg', 556);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('T-Mobile myTouch 4G','The T-Mobile myTouch 4G is a premium smartphone designed to deliver blazing fast 4G speeds so that you can video chat from practically anywhere, with or without Wi-Fi.','img/phones/t-mobile-mytouch-4g.0.jpg', 448);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Samsung Mesmerize™ a Galaxy S™ phone','The Samsung Mesmerize™ delivers a cinema quality experience like you’ve never seen before. Its innovative 4” touch display technology provides rich picture brilliance,even outdoors','img/phones/samsung-mesmerize-a-galaxy-s-phone.0.jpg', 675);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('SANYO ZIO','The Sanyo Zio by Kyocera is an Android smartphone with a combination of ultra-sleek styling, strong performance and unprecedented value.','img/phones/sanyo-zio.0.jpg', 634);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Samsung Transform™','The Samsung Transform™ brings you a fun way to customize your Android powered touch screen phone to just the way you like it through your favorite themed “Sprint ID Service Pack”.','img/phones/samsung-transform.0.jpg', 576);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('T-Mobile G2','The T-Mobile G2 with Google is the first smartphone built for 4G speeds on T-Mobile''s new network. Get the information you need, faster than you ever thought possible.','img/phones/t-mobile-g2.0.jpg', 602);
INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES ('Motorola CHARM™ with MOTOBLUR™','Motorola CHARM fits easily in your pocket or palm.  Includes MOTOBLUR service.','img/phones/motorola-charm-with-motoblur.0.jpg', 644);

-- lst.map(p => "INSERT INTO PRODUCT (NAME, DESCRIPTION, IMAGE, PRICE) VALUES (" + [p.name, p.snippet.replace(/[\r\n]/g, "").replace(/'/g, "''"), p.imageUrl].map(x => "'" + x + "'").join(',') + ", " + Math.round(Math.random() * 500 + 300) + ");").join("\r\n")